path_to_spoof_check_secret_file = '/home/giacomo/VirtualBox VMs/Cartella di passaggio/spoofKey'
uid_field_name= 'uid'
auth_server_address= 'http://localhost:16512'
irma_server_address= 'http://localhost:8088'
