path_to_spoof_check_secret_file = '/home/giacomo/VirtualBox VMs/Cartella di passaggio/spoofKey'
path_to_root_ca_certificate='/home/giacomo/VirtualBox VMs/Cartella di passaggio/rootCA.cert'  #Needed for HTTPS conection with PEP's auth server, as the test environment uses self-signed certs
uid_field_name= 'uid'
auth_server_address= 'http://localhost:8080'
irma_server_address= 'http://localhost:8088'