[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
irma = "0.2.1"
qrcode = "0.12.0"
rand = "0.8.5"
reqwest = "0.11.20"
rocket = "0.5.0-rc.3"
serde_json = "1.0.106"
sha256 = "1.4.0"
toml = "0.7.8"
