---

version: "3"

services:
  pepcli:
    build:
      context: .
      dockerfile: Dockerfile.pepcli
    volumes:
      - ./pep_data:/data
    # Make it interactive:
    stdin_open: true
    tty: true

  irmaserver:
    build:
      context: .
      dockerfile: Dockerfile.irma
    ports:
      - 8088:8088
    volumes:
      # make IRMA schemes persistent, so I can add my own
      - irma-schemes:/root/.local/share/irma/irma_configuration

  irmabuilder:
    build:
      context: ../../irmamobile/docker
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./irma-apk
        target: /root/irmamobile/build/app/outputs/apk
      - type: volume
        read_only: true
        source: irma-schemes
        target: /root/irmamobile/irma_configuration

  identityprovider:
    image: silintl/ssp-base  # https://hub.docker.com/r/silintl/ssp-base
    ports:
      - 8080:80
    env_file:
      - identity_provider_resources/identityprovider.env
    volumes:
      - ./identity_provider_resources/favicon-32x32.png:/data/vendor/simplesamlphp/simplesamlphp/www/favicon.png
      - ./identity_provider_resources/cert:/data/vendor/simplesamlphp/simplesamlphp/cert


  identityprovidertest:
    build:
      context: .
      dockerfile: Dockerfile.identityprovider
    ports:
      - 8081:80
    env_file:
      - identity_provider_resources/identityprovider.env
    volumes:
      - ./identity_provider_resources/favicon-32x32.png:/data/vendor/simplesamlphp/simplesamlphp/www/favicon.png
      - ./identity_provider_resources/cert:/data/vendor/simplesamlphp/simplesamlphp/cert
      - ./identity_provider_resources/config:/data/vendor/simplesamlphp/simplesamlphp/config

volumes:
  irma-schemes:
