version: "3"

services:
  pepcli:
    build:
      context: .
      dockerfile: Dockerfile.pepcli
    volumes:
      - ./pep_data:/data
    # Make it interactive:
    stdin_open: true
    tty: true

  irmaserver:
    build:
      context: .
      dockerfile: Dockerfile.irma
    ports:
      - 8088:8088
    volumes:
      # make IRMA schemes persistent, so I can add my own
      - irma-schemes:/root/.local/share/irma

  irmabuilder:
    build:
      context: ../../irmamobile/docker
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./irma-apk
        target: /root/irmamobile/build/app/outputs/apk
      - type: volume
        read_only: true
        source: irma-schemes/irma_configuration
        target: /root/irmamobile/irma_configuration


volumes:
  irma-schemes:
