path_to_spoof_check_secret_file = '/home/giacomo/VirtualBox VMs/Cartella di passaggio/spoofKey'
path_to_root_ca_certificate='/home/giacomo/VirtualBox VMs/Cartella di passaggio/rootCA.cert'  #Needed for HTTPS conection with PEP's auth server, as the test environment uses self-signed certs
uid_field_name= 'uid'
middleware_auth_server_address= 'http://localhost:8000'
path_to_pepcli= 'resources/pepcli'
column_group= 'Visits'  #Name of the column group the participants are given access to
